-- A Required Extension For Embeddings
create extension if not exists vector;

-- Creating The Segment Table
create table public.segment (
  id bigint generated by default as identity not null,
  speaker text null,
  start real null,
  "end" real null,
  text text null,
  embedding public.vector null,
  constraint segment_pkey primary key (id)
) TABLESPACE pg_default;

--Segment Settings
ALTER TABLE public.segment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.segment FORCE ROW LEVEL SECURITY;

CREATE POLICY "Authentication On Read"
ON public.segment
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "service_role full access"
ON public.segment
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);


-- A Matching Retrieval Function
CREATE OR REPLACE FUNCTION match_segments(
  query_embedding  VECTOR(384),
  speaker_filter   TEXT DEFAULT NULL,
  match_count      INT DEFAULT 5
)
RETURNS TABLE (
  id          BIGINT,
  speaker     TEXT,
  start       REAL,
  "end"       REAL,
  text        TEXT,
  similarity  FLOAT
)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT
    id,
    speaker,
    start,
    "end",
    text,
    1 - (embedding <=> query_embedding) AS similarity
  FROM public.segment
  WHERE (speaker_filter IS NULL OR speaker = speaker_filter)
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;