/*
  To store embeddings we utilize the vector extention
*/
create extension if not exists vector;

/*
  Creating a table storing conversational segments 
*/
create table public.segment (
  id bigint generated by default as identity not null,
  conversation text null,
  speaker text null,
  start real null,
  "end" real null,
  text text null,
  embedding public.vector null,
  constraint segment_pkey primary key (id)
) TABLESPACE pg_default;

/*
  Setting Update/Insert/Read Policy For The Data
 */
ALTER TABLE public.segment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.segment FORCE ROW LEVEL SECURITY;

CREATE POLICY "Authentication On Read" ON public.segment FOR SELECT TO authenticated USING (true);
CREATE POLICY "service_role full access" ON public.segment FOR ALL TO service_role USING (true) WITH CHECK (true);


/*
  A Function To Retrieve The Most Relevant Segments For A Given Query

  query_embedding: the vector to find similar to
  speaker_filter:  filtering by a given speaker
  conversation_filter: filtering by a given conversation
  match_count:   the number of segments to return
*/
CREATE OR REPLACE FUNCTION match_segments(
  query_embedding  VECTOR(384),
  speaker_filter   TEXT DEFAULT NULL,
  conversation_filter TEXT DEFAULT NULL,
  match_count      INT DEFAULT 5
)
RETURNS TABLE (
  id          BIGINT,
  conversation TEXT,
  speaker     TEXT,
  start       REAL,
  "end"       REAL,
  text        TEXT,
  similarity  FLOAT
)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT
    id,
    conversation,
    speaker,
    start,
    "end",
    text,
    1 - (embedding <=> query_embedding) AS similarity
  FROM public.segment
  WHERE (speaker_filter IS NULL OR speaker = speaker_filter)
  AND (conversation_filter IS NULL or conversation = conversation_filter)
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;